url: "https://zacchialun.com"
baseurl: ""

# Site settings
title: Yuriy Zacchia Lun
email: y.zacchialun@gmail.com
description: "Yuriy Zacchia Lun's web page."


# Team names, titles and social links
people:
- name: Yuriy Zacchia Lun, PhD
  pic: 1
  position: Research collaborator at the IMT Lucca
  social:
    - title: linkedin-square
      url: https://www.linkedin.com/in/yuriyzacchialun/?locale=en_US #
    - title: github-square
      url: https://github.com/yuriy-zacchialun/
  sociale:
    - title: orcid-square
      url: https://orcid.org/0000-0002-9408-8773 #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/YuriyZacchiaLun
  - title: instagram
    url: https://www.instagram.com/zacchialun/

# Postal address (add as many lines as necessary)
# address:
#   - line:
#   - line:

# Build settings
markdown: kramdown
permalink: pretty
